// This file is generated automatically by Next.js
// Do not edit this file manually

type AppRoutes = never
type PageRoutes = "/" | "/about" | "/agents" | "/agents/[slug]" | "/blog" | "/blog/[slug]" | "/dashboard" | "/listings" | "/login" | "/news" | "/news/[slug]" | "/properties/[slug]" | "/register" | "/submit-property"
type LayoutRoutes = never
type RedirectRoutes = never
type RewriteRoutes = "/api/[[...path]]" | "/compare/[[...path]]" | "/contact" | "/graphql" | "/newsletter/[[...path]]" | "/security/[[...path]]" | "/wishlist/[[...path]]"
type Routes = AppRoutes | PageRoutes | LayoutRoutes | RedirectRoutes | RewriteRoutes


interface ParamMap {
  "/": {}
  "/about": {}
  "/agents": {}
  "/agents/[slug]": { "slug": string; }
  "/api/[[...path]]": { "path"?: string[]; }
  "/blog": {}
  "/blog/[slug]": { "slug": string; }
  "/compare/[[...path]]": { "path"?: string[]; }
  "/contact": {}
  "/dashboard": {}
  "/graphql": {}
  "/listings": {}
  "/login": {}
  "/news": {}
  "/news/[slug]": { "slug": string; }
  "/newsletter/[[...path]]": { "path"?: string[]; }
  "/properties/[slug]": { "slug": string; }
  "/register": {}
  "/security/[[...path]]": { "path"?: string[]; }
  "/submit-property": {}
  "/wishlist/[[...path]]": { "path"?: string[]; }
}


export type ParamsOf<Route extends Routes> = ParamMap[Route]

interface LayoutSlotMap {
}


export type { AppRoutes, PageRoutes, LayoutRoutes, RedirectRoutes, RewriteRoutes, ParamMap }

declare global {
  /**
   * Props for Next.js App Router page components
   * @example
   * ```tsx
   * export default function Page(props: PageProps<'/blog/[slug]'>) {
   *   const { slug } = await props.params
   *   return <div>Blog post: {slug}</div>
   * }
   * ```
   */
  interface PageProps<AppRoute extends AppRoutes> {
    params: Promise<ParamMap[AppRoute]>
    searchParams: Promise<Record<string, string | string[] | undefined>>
  }

  /**
   * Props for Next.js App Router layout components
   * @example
   * ```tsx
   * export default function Layout(props: LayoutProps<'/dashboard'>) {
   *   return <div>{props.children}</div>
   * }
   * ```
   */
  type LayoutProps<LayoutRoute extends LayoutRoutes> = {
    params: Promise<ParamMap[LayoutRoute]>
    children: React.ReactNode
  } & {
    [K in LayoutSlotMap[LayoutRoute]]: React.ReactNode
  }
}
